// Twilio Voice webhook — returns TwiML that forwards the Google Ads tracking
// number straight through to the real business line. Generated by ads-call-tracking.
// The forward number is the client's public business line (not a secret).
//
// NOTE (compliance): RECORD is on but there is NO caller disclaimer yet.
// Washington is a two-party-consent state — a "this call may be recorded"
// notice to the caller must be added before recording is used in production.
// Operator chose to defer the disclaimer (2026-06-13); add it before relying on recordings.
const FORWARD_TO = "+12068830333"; // brand.phoneRaw — the REAL line that rings
const RECORD = true;               // call recording (operator-approved)

const handler: PagesFunction = () => {
  const rec = RECORD ? ' record="record-from-answer"' : "";
  const twiml =
    `<?xml version="1.0" encoding="UTF-8"?>` +
    `<Response><Dial${rec} answerOnBridge="true"><Number>${FORWARD_TO}</Number></Dial></Response>`;
  return new Response(twiml, { headers: { "Content-Type": "text/xml" } });
};

// Twilio POSTs the webhook; allow GET too for quick browser/Tag-Assistant checks.
export const onRequestPost = handler;
export const onRequestGet = handler;
